name: Deployment

on:
    push:
        branches:
          - master
        paths-ignore:
          - 'docs/**'
          - 'dev/**'

jobs:
    publish_and_deploy:
        name: Publish and Deploy 
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the code
            uses: actions/checkout@v2
          - name: Login to Docker Hub
            run:  make dockerhub-login
            env:
                DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          - name: Retrieve the image
            run: make pkg-build-pull && make pkg-build
          - name: Create Release
            run: make pkg-release 
            env: 
                GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          - name: Publish the image
            run: make pkg-publish
          # - name: Deploy the service
          #   run: make pkg-deploy
